package com.example

import android.app.Application
import android.util.Log
import com.google.firebase.FirebaseApp

class RideTogetherApplication : Application() {

    override fun onCreate() {
        super.onCreate()
        initFirebase()
    }

    private fun initFirebase() {
        try {
            if (FirebaseApp.getApps(this).isEmpty()) {
                // Relies directly on resources generated by com.google.gms.google-services from google-services.json
                FirebaseApp.initializeApp(this)
                Log.i("RideTogetherApp", "FirebaseApp initialized from google-services resources")
            } else {
                Log.i("RideTogetherApp", "FirebaseApp already initialized by ContentProvider")
            }
        } catch (e: Exception) {
            Log.e("RideTogetherApp", "Firebase initialization error: ${e.message}", e)
        }
    }
}
